POST http://localhost:8080/add
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyIiwiZXhwIjoxNjM0NTAwMDcwLCJpYXQiOjE2MDI5NjQwNzB9.1HLjqDbZz5VN6B268zQA5CVCQ0maYmyaWcY6YOMoMow
Content-Type: application/json

{
  "restaurantId": 3,
  "orderId": 37,
  "userName": "Leonid Sidorov",
  "dishes": [
    {
      "name": "ponchik",
      "qty": 5,
      "price": 1.5
    },
    {
      "name": "salo",
      "qty": 1,
      "price": 89
    },
    {
      "name": "kompot",
      "qty": 8,
      "price": 9
    }
  ]
}